[package]
name = "lib-crate"
version = "0.1.0"
edition = "2021"


[dependencies]

tokio = { version = "1.7.1", features = ["macros", "rt","rt-multi-thread", "sync", "test-util"] }
monoio = { version = "0.1.0", features = [] }
tracing = "0.1.29"
